# [dbo].[Blog]

In [0]:
USE [myDemoDB]
GO

In [0]:
/****** Object:  Table [dbo].[Blog]    Script Date: 2022/12/19 下午 02:45:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Blog](
	[文章編號] [int] NOT NULL,
	[發言者ID] [int] NULL,
	[樓層] [int] NULL,
	[評論內容] [nvarchar](200) NULL,
	[留言時間] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[文章編號] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[日程表]

In [0]:
/****** Object:  Table [dbo].[日程表]    Script Date: 2022/12/19 下午 02:45:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[日程表](
	[日期] [date] NOT NULL,
	[租借負責人ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[日期] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[訂單01]

In [0]:
/****** Object:  Table [dbo].[訂單01]    Script Date: 2022/12/19 下午 02:45:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[訂單01](
	[訂單編號] [int] NOT NULL,
	[購買人ID] [int] NULL,
	[購買商品ID] [int] NULL,
	[購買商品名稱] [nvarchar](50) NULL,
	[購買數量] [int] NULL,
	[此筆訂單折扣] [float] NULL,
	[實收金額] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[訂單編號] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[食譜01]

In [0]:
/****** Object:  Table [dbo].[食譜01]    Script Date: 2022/12/19 下午 02:45:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[食譜01](
	[食譜ID] [int] NOT NULL,
	[商品ID] [int] NULL,
	[商品名稱] [nvarchar](50) NULL,
	[食譜內容] [nvarchar](50) NULL,
	[影片位址] [varchar](200) NULL,
	[文檔名稱] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[食譜ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[商品HashTag01]

In [0]:
/****** Object:  Table [dbo].[商品HashTag01]    Script Date: 2022/12/19 下午 02:45:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[商品HashTag01](
	[商品ID] [int] NULL,
	[HashTag] [nvarchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[商品資料更新01]

In [0]:
/****** Object:  Table [dbo].[商品資料更新01]    Script Date: 2022/12/19 下午 02:45:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[商品資料更新01](
	[商品ID] [int] NOT NULL,
	[商品名稱] [nvarchar](50) NULL,
	[商品份數/口味] [nvarchar](50) NULL,
	[商品定價] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[商品ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[會員資訊]

In [0]:
/****** Object:  Table [dbo].[會員資訊]    Script Date: 2022/12/19 下午 02:45:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[會員資訊](
	[會員ID] [int] NOT NULL,
	[姓名] [nvarchar](50) NULL,
	[暱稱] [nvarchar](50) NULL,
	[Email] [varchar](50) NULL,
	[手機號碼] [varchar](50) NULL,
	[密碼] [varchar](50) NULL,
	[密碼提示題目編號] [int] NULL,
	[密碼提示答案] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[會員ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[日程表]

In [0]:
INSERT [dbo].[日程表] ([日期], [租借負責人ID]) VALUES (CAST(N'2023-02-08' AS Date), 3)
INSERT [dbo].[日程表] ([日期], [租借負責人ID]) VALUES (CAST(N'2023-02-09' AS Date), 5)
GO

# [dbo].[訂單01]

In [0]:
INSERT [dbo].[訂單01] ([訂單編號], [購買人ID], [購買商品ID], [購買商品名稱], [購買數量], [此筆訂單折扣], [實收金額]) VALUES (1, 5, 8, N'巧克力球', 3, 0, 900)
INSERT [dbo].[訂單01] ([訂單編號], [購買人ID], [購買商品ID], [購買商品名稱], [購買數量], [此筆訂單折扣], [實收金額]) VALUES (2, 9, 16, N'檸檬瑪德蓮', 10, 0, 2700)
INSERT [dbo].[訂單01] ([訂單編號], [購買人ID], [購買商品ID], [購買商品名稱], [購買數量], [此筆訂單折扣], [實收金額]) VALUES (3, 8, 20, N'酒鬼先生', 5, 0, 700)
GO

# [dbo].[食譜01]

In [0]:
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (1, 1, N'cheese餅餅', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (2, 3, N'波卡米餅', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (3, 4, N'舔嘴杏仁餅', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (4, 5, N'蔓越莓司康', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (5, 6, N'百香可可旅人蛋糕', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (6, 7, N'巧克力球', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (7, 10, N'天使之鈴可麗露', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (8, 12, N'泡芙', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (9, 16, N'檸檬瑪德蓮', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (10, 17, N'檸夏檸檬塔', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (11, 18, N'酒鬼芭娜娜', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (12, 20, N'酒鬼先生', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (13, 22, N'裝熟乳酪', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (14, 23, N'巧克力莓果塔', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
INSERT [dbo].[食譜01] ([食譜ID], [商品ID], [商品名稱], [食譜內容], [影片位址], [文檔名稱]) VALUES (15, 24, N'酒漬櫻桃黑森林', N'自己GOOGLE', N'自己GOOGLE', N'自己GOOGLE')
GO

# [dbo].[商品HashTag01]

In [0]:
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (1, N'起司/餅餅/甜嘴/零嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (2, N'起司/餅餅/甜嘴/零嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (3, N'寶寶/米餅/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (4, N'杏仁餅/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (5, N'蔓越莓/司康/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (6, N'可可/巧克力/百香/蛋糕/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (7, N'可可/巧克力/脆片/杏仁/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (8, N'可可/巧克力/脆片/杏仁/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (9, N'可麗露/可可/櫻桃/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (10, N'可麗露/可可/櫻桃/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (11, N'可麗露/可可/櫻桃/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (12, N'泡芙/草莓/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (13, N'泡芙/伯爵/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (14, N'泡芙/香草/奶油/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (15, N'泡芙/可可/巧克力/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (16, N'檸檬/瑪德蓮/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (17, N'檸檬/S檸檬塔/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (18, N'香蕉/提拉米蘇/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (19, N'香蕉/提拉米蘇/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (20, N'提拉米蘇/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (21, N'提拉米蘇/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (22, N'乳酪/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (23, N'巧克力/莓果/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (24, N'酒漬/櫻桃/黑森林/巧克力/甜嘴')
INSERT [dbo].[商品HashTag01] ([商品ID], [HashTag]) VALUES (25, N'酒漬/櫻桃/黑森林/巧克力/甜嘴')
GO

# [dbo].[商品資料更新01]

In [0]:
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (1, N'cheese餅餅', N'小罐', 120)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (2, N'cheese餅餅', N'大罐', 220)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (3, N'波卡米餅', N'800g', 200)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (4, N'舔嘴杏仁餅', N'11入', 300)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (5, N'蔓越莓司康', N'6入', 350)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (6, N'百香可可旅人蛋糕', N'5入', 350)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (7, N'巧克力球', N'金光閃閃/10入', 250)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (8, N'巧克力球', N'粉紅泡泡/10入', 300)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (9, N'天使之鈴可麗露', N'櫻桃可可/6入', 450)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (10, N'天使之鈴可麗露', N'經典原味/6入', 450)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (11, N'天使之鈴可麗露', N'綜合/6入', 450)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (12, N'泡芙', N'草莓起司/6入', 400)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (13, N'泡芙', N'伯爵茶/6入', 400)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (14, N'泡芙', N'香草奶油/6入', 400)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (15, N'泡芙', N'香濃可可/6入', 400)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (16, N'檸檬瑪德蓮', N'6入', 270)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (17, N'檸夏檸檬塔', N'顆', 90)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (18, N'酒鬼芭娜娜', N'小杯裝', 140)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (19, N'酒鬼芭娜娜', N'大盒裝', 520)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (20, N'酒鬼先生', N'小杯裝', 140)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (21, N'酒鬼先生', N'大盒裝', 520)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (22, N'裝熟乳酪', N'5入', 350)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (23, N'巧克力莓果塔', N'顆', 150)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (24, N'酒漬櫻桃黑森林', N'小杯裝', 140)
INSERT [dbo].[商品資料更新01] ([商品ID], [商品名稱], [商品份數/口味], [商品定價]) VALUES (25, N'酒漬櫻桃黑森林', N'大盒裝', 520)
GO

# [dbo].[會員資訊]

In [0]:
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (1, N'張育剛', N'Peter', N'FERvvbvty0P@gmail.com', N'0912100521', N'a001', 1, N'寵物生日')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (2, N'賴惠悅', N'Julia', N'LwxffoPPgmq@gmail.com', N'0952153625', N'a002', 1, N'寵物生日')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (3, N'王大富', N'Wang', N'qk2rcmWv1a@gmail.com', N'0945126369', N'a003', 2, N'老婆生日')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (4, N'林雅婷', N'採青', N'rDlIDrL385EdE@gmail.com', N'09874561232', N'a004', 3, N'門牌號碼')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (5, N'蔡志文', N'夏山', N'Kr5zt1eyD6JJ@gmail.com', N'0914521652', N'a005', 4, N'提款卡號碼')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (6, N'張育南', N'逍遙', N'cLxjgOtlQ5@gmail.com', N'0988522147', N'a006', 5, N'幸運數字')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (7, N'王欣儀', N'靈兒', N'rri5Ijko0k5eC@gmail.com', N'0966321581', N'a007', 5, N'幸運數字')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (8, N'張嘉麟', N'Allen', N'FSe5NObYOP@gmail.com', N'0932789415', N'a008', 3, N'門牌號碼')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (9, N'顏宗憲', N'Patrick', N'g40AGSVX3fZS@gmail.com', N'0921587456', N'a009', 4, N'提款卡號碼')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (10, N'劉雅雅', N'Ella', N'g40AGSVX3fZS@gmail.com', N'0914784952', N'a010', 2, N'老婆生日')
INSERT [dbo].[會員資訊] ([會員ID], [姓名], [暱稱], [Email], [手機號碼], [密碼], [密碼提示題目編號], [密碼提示答案]) VALUES (11, N'許品康', N'Will', N'cPM6picI@gmail.com', N'0909212153', N'a011', 4, N'提款卡號碼')
GO

# [FK__Blog__發言者ID__2F10007B]

In [0]:
ALTER TABLE [dbo].[Blog]  WITH CHECK ADD FOREIGN KEY([發言者ID])
REFERENCES [dbo].[會員資訊] ([會員ID])
GO

# [FK__日程表__租借負責人ID__300424B4]

In [0]:
ALTER TABLE [dbo].[日程表]  WITH CHECK ADD FOREIGN KEY([租借負責人ID])
REFERENCES [dbo].[會員資訊] ([會員ID])
GO